### ISSUE TITLE
Design the jumping/climbing animations for the Main Character

### ISSUE THREAD

**Issue by s160210** [UoSGamesGroups/first-semester-l4-5-group-13#25]
Design the jumping/climbing animations for the Main Character. Follow the same style as the other animations already created. Some added humour was discussed. This could be a nice addition. 

Assigned Time: 2 Hours

**Comment by s175444** [comment]
The animations for Climbing (top) and jumping (bottom)
![tophat_climbing](https://cloud.githubusercontent.com/assets/22791354/19855878/b4abd664-9f6e-11e6-8f7b-94d242ff7769.png)
![tophat_jump](https://cloud.githubusercontent.com/assets/22791354/19855881/b6670096-9f6e-11e6-922d-a1e9bad892c9.png)
