### ISSUE TITLE
Design the layout blueprints for 6 chunks

### ISSUE THREAD

**Issue by s160210** [UoSGamesGroups/first-semester-l4-5-group-13#3]
Design the layout for 6 individual level chunks. These layouts should be finalized and ready for an artist to begin re-creating with finished art assets. You are not expected to create art. You are allowed to use rudimentary placeholder assets. The important thing is that the design of the chunks are finalized. 

Time allocation: 3 hours

**Comment by EatTheFoodTina** [comment]
![4](https://cloud.githubusercontent.com/assets/9140500/19701811/e9c278b8-9af4-11e6-8909-677c3df1520e.JPG)
![5](https://cloud.githubusercontent.com/assets/9140500/19701810/e9c13be2-9af4-11e6-8498-20ae4ee8da9b.JPG)
![6](https://cloud.githubusercontent.com/assets/9140500/19701808/e9c047fa-9af4-11e6-977e-3edcf336e4e7.JPG)
![1](https://cloud.githubusercontent.com/assets/9140500/19701809/e9c1128e-9af4-11e6-9140-bb3975e5e330.JPG)
![2](https://cloud.githubusercontent.com/assets/9140500/19701807/e9c0144c-9af4-11e6-9fa6-65567c89bb65.JPG)
![3](https://cloud.githubusercontent.com/assets/9140500/19701806/e9c014f6-9af4-11e6-9e93-d1ea33b3ea55.JPG)
