### ISSUE TITLE
Design the layout blueprint for the storefront

### ISSUE THREAD

**Issue by s160210** [UoSGamesGroups/first-semester-l4-5-group-13#5]
Design the layout for the storefront. This layout should be finalized and ready for an artist to begin re-creating with finished art assets. You are not expected to create art. You are allowed to use rudimentary placeholder assets. The important thing is that the design for the storefront is finalized.

Time allocation: 3 hours

**Comment by EatTheFoodTina** [comment]
![store front](https://cloud.githubusercontent.com/assets/9140500/19701784/d5218f7a-9af4-11e6-9661-793a8f21643c.JPG)
