### ISSUE TITLE
Concept ideas for our Main Character

### ISSUE THREAD

**Issue by s160210** [UoSGamesGroups/first-semester-l4-5-group-13#7]
Concept ideas for our Main Character. You should try to come up with a few ideas at least. Once you have these ideas, the group will vote on their favorite and you can move on to the next part of this task.

Time allocation: 1 hour 30 minutes

**Comment by s175444** [comment]
Ok, got four ideas down ready for voting. The finished versions will be considerably smaller but will be as close design wise as I can get.

As the drawings can only get so much across, I'll elaborate a little on the designs. 
'Grandpa' is supposed to be a lot more active than he may look, and clearly an antiques expert. He may not look very with it but it's a complete bluff and he's merciless with hagglers.

'The curator' is supposed to be a bit like David Dickenson (see almost any antiques tv show on BBC) only younger. He's probably the closest to the real thing, and thanks to being younger than Grandpa he actually looks like he could do all the adventuring that will happen in the game.

'The Bookeeper', while probably the youngest was still supposed to look like they know what they're doing when it comes to antiques-or if they don't, to be so intimidating/quietly confident that the customer doesn't even notice. 

'Top hat' is meant to practically blaze with charisma, and would probably look best suited for all the jumping around and adventuring.

![concept 1](https://cloud.githubusercontent.com/assets/22791354/19571391/eb5cd374-96f5-11e6-9835-dac36cc84694.png)
![concept 2](https://cloud.githubusercontent.com/assets/22791354/19571392/eb6000f8-96f5-11e6-8904-0d14026c94c2.png)

While I will say this again on the email anyway, vote for the three designs you like best, ranking them from best to worst. The one with the most votes will be our chosen character. I already know which I like best but I will not skew the votes by stating which until the rest of the votes are in.

**Comment by s184252** [comment]
(Ken here)
My vote:
1. Grandpa
2. Top Hat
3. The Curator

**Comment by EatTheFoodTina** [comment]
(Tom)
1.Top Hat
2.The Curator
3. Grandpa
