### ISSUE TITLE
Using the results from the group vote, create the finalized Main Character art

### ISSUE THREAD

**Issue by s160210** [UoSGamesGroups/first-semester-l4-5-group-13#8]
Using the results from the group vote, create the finalized Main Character art. This should be game ready. 

Time allocation: 1 hour 30 minutes

**Comment by s175444** [comment]
Right, this should be a pretty good version of the finished sprite. It's also a two frame idle animation, probably  best to play at a slow speed. The shading has been modified to come from the same direction even when facing the other way. While I can also do this for the walk cycle, if you guys aren't worried about it I can just flip the animation instead. And if you have any other ideas or suggestions for improving it, please let me know.

![tophat_idle](https://cloud.githubusercontent.com/assets/22791354/19625677/05ee76de-9917-11e6-89b2-5d97d9348d1e.png)

**Comment by s160210** [comment]
That looks pretty good Doug! Nice work. If the task is done, can you throw the 'issue card' into the done section please?
